In [1]:
import numpy as np

In [2]:
los = np.random.RandomState(100)

In [3]:
liczby = los.randint(-100,100,1000000)

In [4]:
liczby

array([-92, -76, -33, ...,  90, -61,  61])

###### Z1: Stwórz wektor wartości powiększony o 20 - używamy list comprehensions!

In [6]:
np.array([each + 20 for each in liczby])

array([-72, -56, -13, ..., 110, -41,  81])

In [25]:

lista = []
for each in liczby:
    lista.append(each+20)
lista = np.array(lista)
    
lista

array([-72, -56, -13, ..., 110, -41,  81])

###### Z2: Wektor takich wartości, które są większe od zera

In [24]:
np.array([each for each in liczby if each > 0])

array([ 3, 76, 38, ..., 54, 90, 61])

In [20]:
lista = []
for each in liczby:
    if each >0:
        lista.append(each)
lista = np.array(lista)

In [21]:
lista

array([ 3, 76, 38, ..., 54, 90, 61])

###### Z3: Wektor wartości podniesionych do kwadratu, ale tylko jeśli oryginalna wartość była większa od 50

In [18]:
lista = []
for each in liczby:
    if each > 50:
        lista.append(each*each)
lista = np.array(lista)

lista

array([5776, 6400, 3025, ..., 2916, 8100, 3721])

In [14]:
np.array([each*each for each in liczby if each > 50])

array([5776, 6400, 3025, ..., 2916, 8100, 3721])

###### Z4: Wektor wartości, w którym:
1. wartości większe od zera są podniesione do kwadratu
2. pozostałe wartości pozostają niezmienione
3. zapisz do zmiennej lc

In [22]:
lista = []
for each in liczby:
    if each >0:
        lista.append(each**2)
    else:
        lista.append(each)

np.array(lista)

array([ -92,  -76,  -33, ..., 8100,  -61, 3721])

In [27]:
Ic = np.array([each **2 if each > 0 else each for each in liczby ])

###### Z5: Wektor wartości parzystych z wektora lc

In [28]:
Ic

array([ -92,  -76,  -33, ..., 8100,  -61, 3721])

In [30]:
np.array([each for each in liczby if each % 2 == 0])

array([-92, -76,  76, ...,  56,  54,  90])

###### Z6: Wektor wartości nieparzystych z wektora lc

In [31]:
np.array([each for each in liczby if each % 2 != 0])

array([-33,   3, -13, ...,  -9, -61,  61])

###### Z7: Słownik, w którym hasłem jest liczba a znaczeniem informacja czy dana liczba jest parzysta czy nieparzysta

In [32]:
{each : ('parzysta' if each  % 2 == 0 else 'nieparzysta') for each in Ic}

{-100: 'parzysta',
 -99: 'nieparzysta',
 -98: 'parzysta',
 -97: 'nieparzysta',
 -96: 'parzysta',
 -95: 'nieparzysta',
 -94: 'parzysta',
 -93: 'nieparzysta',
 -92: 'parzysta',
 -91: 'nieparzysta',
 -90: 'parzysta',
 -89: 'nieparzysta',
 -88: 'parzysta',
 -87: 'nieparzysta',
 -86: 'parzysta',
 -85: 'nieparzysta',
 -84: 'parzysta',
 -83: 'nieparzysta',
 -82: 'parzysta',
 -81: 'nieparzysta',
 -80: 'parzysta',
 -79: 'nieparzysta',
 -78: 'parzysta',
 -77: 'nieparzysta',
 -76: 'parzysta',
 -75: 'nieparzysta',
 -74: 'parzysta',
 -73: 'nieparzysta',
 -72: 'parzysta',
 -71: 'nieparzysta',
 -70: 'parzysta',
 -69: 'nieparzysta',
 -68: 'parzysta',
 -67: 'nieparzysta',
 -66: 'parzysta',
 -65: 'nieparzysta',
 -64: 'parzysta',
 -63: 'nieparzysta',
 -62: 'parzysta',
 -61: 'nieparzysta',
 -60: 'parzysta',
 -59: 'nieparzysta',
 -58: 'parzysta',
 -57: 'nieparzysta',
 -56: 'parzysta',
 -55: 'nieparzysta',
 -54: 'parzysta',
 -53: 'nieparzysta',
 -52: 'parzysta',
 -51: 'nieparzysta',
 -50: 'parzysta',
 -49: 

###### Z8: Słownik, w którym hasłem jest liczba a znaczeniem informacja czy dana liczba jest podzielna czy niepodzielna przez 16. Zapisz do zmiennej s16

In [34]:
s16 = {each : ('podzielna_przez_16' if each  % 16 == 0 else 'niepodzielna_przez_16') for each in Ic}

###### Z9: Wektor wartości podzielnych przez 16 ze słownika s16

In [35]:
s16.keys()

dict_keys([-92, -76, -33, 9, -13, -21, 5776, 1444, -6, 6400, -2, -47, -34, -86, -66, 1849, 49, -40, -42, 1936, 1369, -7, -14, 900, 3025, 64, 1024, 3481, 841, 1681, 0, -96, -9, 7569, 1225, -51, 5625, 8649, -39, 6889, 9801, -20, -98, 441, 25, 2209, -37, 6561, -73, -44, 169, 3364, -53, 4489, 81, -62, 5184, -82, 8464, 7056, 3844, -83, -28, -87, 36, -70, -32, 6084, -22, -100, 7225, 961, -30, 7744, -57, -64, -95, -29, 4900, -16, -5, 196, 361, -24, -67, 4, 2500, 9216, 8100, -50, 3969, 2601, -91, -79, 2809, 6724, -94, 4225, 484, 256, 7396, -61, -49, 2704, -55, -11, 5329, -65, -84, -88, -80, 1600, 2116, -8, -56, -43, 729, -27, 1089, 6241, -10, 9025, -23, 225, 2304, 4624, -72, 2025, -26, 3136, -18, -19, 289, -75, 8836, -89, 1, -78, -45, -58, -17, 7921, -63, 144, -1, -38, 5929, 121, 1521, -71, 2916, -48, 4096, -15, 676, 529, -52, -68, -60, 1764, 784, 16, -59, -35, -90, -74, 3721, -12, -41, -85, 1156, 100, 5476, 9409, -36, -25, 576, -4, -81, 4761, -54, -93, -77, -99, 400, 3600, 4356, 1296, -69, -9

In [36]:
s16.values()

dict_values(['niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'podzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'podzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'podzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'podzielna_przez_16', 'podzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'podzielna_przez_16', 'podzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodzielna_przez_16', 'niepodz

In [ ]:
# trzeba zrobić list[s16.values()] żeby móc adresować po indeksie (odwoływać się)

In [37]:
np.array([each for each in s16.keys() if each % 16 == 0])

array([5776, 6400, 1936,   64, 1024,    0,  -96, 5184, 8464, 7056,  -32,
       7744,  -64,  -16, 9216,  256, 2704,  -80, 1600, 2304, 4624, 3136,
        144,  -48, 4096,  784,   16,  576,  400, 3600, 1296])

###### Z10: Wektor wartości niepodzielnych przez 16 ze słownika s16

In [38]:
np.array([each for each in s16.keys() if each % 16 != 0])

array([ -92,  -76,  -33,    9,  -13,  -21, 1444,   -6,   -2,  -47,  -34,
        -86,  -66, 1849,   49,  -40,  -42, 1369,   -7,  -14,  900, 3025,
       3481,  841, 1681,   -9, 7569, 1225,  -51, 5625, 8649,  -39, 6889,
       9801,  -20,  -98,  441,   25, 2209,  -37, 6561,  -73,  -44,  169,
       3364,  -53, 4489,   81,  -62,  -82, 3844,  -83,  -28,  -87,   36,
        -70, 6084,  -22, -100, 7225,  961,  -30,  -57,  -95,  -29, 4900,
         -5,  196,  361,  -24,  -67,    4, 2500, 8100,  -50, 3969, 2601,
        -91,  -79, 2809, 6724,  -94, 4225,  484, 7396,  -61,  -49,  -55,
        -11, 5329,  -65,  -84,  -88, 2116,   -8,  -56,  -43,  729,  -27,
       1089, 6241,  -10, 9025,  -23,  225,  -72, 2025,  -26,  -18,  -19,
        289,  -75, 8836,  -89,    1,  -78,  -45,  -58,  -17, 7921,  -63,
         -1,  -38, 5929,  121, 1521,  -71, 2916,  -15,  676,  529,  -52,
        -68,  -60, 1764,  -59,  -35,  -90,  -74, 3721,  -12,  -41,  -85,
       1156,  100, 5476, 9409,  -36,  -25,   -4,  -

In [39]:
#### można dłużej odwołując się dwóch zbiorów

np.array([each for index, 
          each in 
          enumerate(s16.keys()) 
          if list(s16.values())[index]  == 'niepodzielna_przez_16'])

array([ -92,  -76,  -33,    9,  -13,  -21, 1444,   -6,   -2,  -47,  -34,
        -86,  -66, 1849,   49,  -40,  -42, 1369,   -7,  -14,  900, 3025,
       3481,  841, 1681,   -9, 7569, 1225,  -51, 5625, 8649,  -39, 6889,
       9801,  -20,  -98,  441,   25, 2209,  -37, 6561,  -73,  -44,  169,
       3364,  -53, 4489,   81,  -62,  -82, 3844,  -83,  -28,  -87,   36,
        -70, 6084,  -22, -100, 7225,  961,  -30,  -57,  -95,  -29, 4900,
         -5,  196,  361,  -24,  -67,    4, 2500, 8100,  -50, 3969, 2601,
        -91,  -79, 2809, 6724,  -94, 4225,  484, 7396,  -61,  -49,  -55,
        -11, 5329,  -65,  -84,  -88, 2116,   -8,  -56,  -43,  729,  -27,
       1089, 6241,  -10, 9025,  -23,  225,  -72, 2025,  -26,  -18,  -19,
        289,  -75, 8836,  -89,    1,  -78,  -45,  -58,  -17, 7921,  -63,
         -1,  -38, 5929,  121, 1521,  -71, 2916,  -15,  676,  529,  -52,
        -68,  -60, 1764,  -59,  -35,  -90,  -74, 3721,  -12,  -41,  -85,
       1156,  100, 5476, 9409,  -36,  -25,   -4,  -