In [2]:
import numpy as np

In [3]:
los = np.random.RandomState(100)

In [4]:
liczby = los.randint(-100,100,1000000)

In [5]:
liczby

array([-92, -76, -33, ...,  90, -61,  61])

###### Z1: Stwórz wektor wartości powiększony o 20 - używamy list comprehensions!

In [17]:
liczby20 = liczby + 20
liczby_plus_20 = np.array([each+20 for each in liczby])
liczby_plus_20

array([-72, -56, -13, ..., 110, -41,  81])

In [18]:
np.around(np.mean(liczby_plus_20))

20.0

###### Z2: Wektor takich wartości, które są większe od zera

In [27]:
liczby_wieksze_od_0 = liczby[liczby > 0]
wieksze_od_0 = np.array([each for each in liczby if each > 0])
wieksze_od_0

array([ 3, 76, 38, ..., 54, 90, 61])

In [28]:
liczby_wieksze_od_0

array([ 3, 76, 38, ..., 54, 90, 61])

###### Z3: Wektor wartości podniesionych do kwadratu, ale tylko jeśli oryginalna wartość była większa od 50

In [30]:
liczby_wieksze_od_50_do_kwadratu = liczby[liczby > 50] **2
liczby_wieksze_od_50_do_kwadratu

array([5776, 6400, 3025, ..., 2916, 8100, 3721], dtype=int32)

In [29]:
wieksze_od_50_do_kwadratu = np.array([each **2 for each in liczby if each > 50])
wieksze_od_50_do_kwadratu

array([5776, 6400, 3025, ..., 2916, 8100, 3721])

###### Z4: Wektor wartości, w którym:
1. wartości większe od zera są podniesione do kwadratu
2. pozostałe wartości pozostają niezmienione
3. zapisz do zmiennej lc

In [41]:
Ic = np.array([each **2 if each > 0 else each for each in liczby ])
Ic

array([ -92,  -76,  -33, ..., 8100,  -61, 3721])

In [42]:
Ic.mean()

1620.457557

###### Z5: Wektor wartości parzystych z wektora lc

In [45]:
parzyste = np.array([each for each in Ic if each % 2 == 0])
parzyste

array([ -92,  -76, 5776, ..., 3136, 2916, 8100])

In [46]:
parzyste.mean()

1596.3932955079904

###### Z6: Wektor wartości nieparzystych z wektora lc

In [47]:
nieparzyste = np.array([each for each in Ic if each % 2 != 0])
nieparzyste

array([ -33,    9,  -13, ...,   -9,  -61, 3721])

In [48]:
nieparzyste.mean()

1644.4895939720388

###### Z7: Słownik, w którym hasłem jest liczba a znaczeniem informacja czy dana liczba jest parzysta czy nieparzysta

###### Z8: Słownik, w którym hasłem jest liczba a znaczeniem informacja czy dana liczba jest podzielna czy niepodzielna przez 16. Zapisz do zmiennej s16

###### Z9: Wektor wartości podzielnych przez 16 ze słownika s16

###### Z10: Wektor wartości niepodzielnych przez 16 ze słownika s16