In [1]:
import numpy as np

In [ ]:
def NAZWA_FUNKCJI(argument1, a2, a3, ..., an):
    bla bla bla
    return NAZWA_ZMIENNEJ

In [2]:
def sumuj(x,y):
    suma = x + y
    return suma

In [3]:
sumuj(5,7)

12

In [4]:
wynik = sumuj(10,40)
wynik

50

In [5]:
sumuj

<function __main__.sumuj>

In [6]:
sumuj()

TypeError: sumuj() missing 2 required positional arguments: 'x' and 'y'

In [24]:
def sumuj(x=5,y=100):
    suma = x+ y
    return suma

In [12]:
sumuj(x=1000)

100

In [9]:
def sumuj_odejmuj(x,y):
    s = x + y
    o = x - y
    return s, o

In [10]:
sumuj_odejmuj(10,3)

(13, 7)

In [13]:
wynik2 = sumuj_odejmuj(10, 3) # (...) o tuple

In [17]:
suma, odejmowanie = sumuj_odejmuj(10,3)

In [18]:
suma

13

In [19]:
odejmowanie

7

In [20]:
#losujemy dane
seed = np.random.RandomState(1)

In [21]:
l = seed.normal(size=100)
l

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521,
       -1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547,
       -0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
       -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
       -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
       -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311,
        0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
        0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116,
       -0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
       -0.07557171,  1.13162939,  1.51981682,  2.18557541, -1.39

In [36]:
# x - M = Z * SD
# x = Z * SD + M

def odstandaryzowywanie(Z, SD, M):
    x = Z*SD + M
    decimals = 0
    return x

In [42]:
    SD = 15
    M = 100
    Z = l

In [43]:
#odstandaryzowywanie(Z, SD, M)

odstandaryzowywanie (l, 15, 100)

array([ 124.36518045,   90.8236538 ,   92.07742372,   83.90547067,
        112.98111444,   65.47691955,  126.17217646,   88.58189649,
        104.78558644,   96.25944437,  121.93161906,   69.09788936,
         95.16374194,   94.23918468,  117.00654164,   83.50163099,
         97.41357689,   86.83212373,  100.6332062 ,  108.74222821,
         83.49071234,  117.17085565,  113.52386081,  107.53741508,
        113.51283924,   89.74408211,   98.15664662,   85.96345849,
         95.98167881,  107.955332  ,   89.62508872,   94.0486971 ,
         89.6924095 ,   87.32191538,   89.93130804,   99.81003102,
         83.24034477,  103.51623547,  124.89703266,  111.13066241,
         97.12246671,   86.68556554,   88.79262559,  125.38681902,
        100.76211632,   90.4450653 ,  102.86373227,  131.50382705,
        101.80238429,  109.25804665,  104.5025548 ,   94.7162523 ,
         82.86222703,   94.75985916,   96.8665865 ,  108.79934787,
        112.58475121,  113.96653122,  104.28380988,  113.27711

In [49]:
def odstandaryzowywanie(Z, SD, M, decimals=0):
    x = Z*SD + M
    decimals = 0
    return x

In [50]:
def odstandaryzowywanie(Z, SD, M, decimals=0):
    # trzeba się upewnić czy numpy wczytany, więc na wszelki wypadek
    import numpy as np
    x = np.round(Z*SD + M, decimals = decimals) # bo domyślnie decimals okazuje sie być 0
    return x

In [52]:
odstandaryzowywanie(Z=l, M=100, SD=15)
# można zapisać też tak x(l, 100, 15)

array([ 124.,   91.,   92.,   84.,  113.,   65.,  126.,   89.,  105.,
         96.,  122.,   69.,   95.,   94.,  117.,   84.,   97.,   87.,
        101.,  109.,   83.,  117.,  114.,  108.,  114.,   90.,   98.,
         86.,   96.,  108.,   90.,   94.,   90.,   87.,   90.,  100.,
         83.,  104.,  125.,  111.,   97.,   87.,   89.,  125.,  101.,
         90.,  103.,  132.,  102.,  109.,  105.,   95.,   83.,   95.,
         97.,  109.,  113.,  114.,  104.,  113.,   89.,  119.,  108.,
         96.,  107.,   99.,  117.,  123.,  133.,   79.,   78.,   92.,
        102.,  113.,  105.,   70.,   95.,  112.,  103.,  111.,   97.,
         97.,  103.,  106.,  103.,  102.,   90.,  106.,  102.,  117.,
        118.,  103.,   94.,   90.,  106.,  101.,   95.,  101.,   91.,  110.])

In [53]:
odstandaryzowywanie(Z=l, M=100, SD=15, decimals = 2)

array([ 124.37,   90.82,   92.08,   83.91,  112.98,   65.48,  126.17,
         88.58,  104.79,   96.26,  121.93,   69.1 ,   95.16,   94.24,
        117.01,   83.5 ,   97.41,   86.83,  100.63,  108.74,   83.49,
        117.17,  113.52,  107.54,  113.51,   89.74,   98.16,   85.96,
         95.98,  107.96,   89.63,   94.05,   89.69,   87.32,   89.93,
         99.81,   83.24,  103.52,  124.9 ,  111.13,   97.12,   86.69,
         88.79,  125.39,  100.76,   90.45,  102.86,  131.5 ,  101.8 ,
        109.26,  104.5 ,   94.72,   82.86,   94.76,   96.87,  108.8 ,
        112.58,  113.97,  104.28,  113.28,   88.68,  118.79,  107.69,
         95.53,  107.33,   98.87,  116.97,  122.8 ,  132.78,   79.05,
         78.34,   92.43,  102.4 ,  113.14,  104.73,   69.67,   95.41,
        112.42,  103.45,  111.43,   96.67,   96.99,  102.8 ,  106.15,
        102.97,  101.79,   89.94,  105.66,  101.83,  116.94,  117.98,
        102.78,   94.37,   90.42,  106.35,  101.16,   94.84,  100.65,
         90.7 ,  110